{% set name = "dantro" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 682b1f37f2fe928804d2508543e012705b6e6e35fd25a57d34d92131f080b269

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask
    - distributed
    - h5py
    - h5netcdf
    - matplotlib-base
    - networkx
    - numpy
    - ruamel.yaml
    - scipy
    - sympy
    - toolz
    - xarray
    - paramspace
    - dill
    - seaborn

test:
  imports:
    - dantro
    - dantro.containers
    - dantro.data_loaders
    - dantro.data_ops
    - dantro.groups
    - dantro.mixins
    - dantro.plot.creators
    - dantro.plot.funcs
    - dantro.proxy
    - dantro.utils
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://gitlab.com/utopia-project/dantro
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Handle, transform, and visualize hierarchically structured data
  description: |
    dantro is a python package for handling, transforming, and visualizing
    hierarchically organized data.
    Integrated into data-intensive projects, it supplies an easy way to define
    a customizable, configuration-based data processing pipeline.
  doc_url: https://dantro.readthedocs.io
  dev_url: https://gitlab.com/utopia-project/dantro

extra:
  recipe-maintainers:
    - blsqr
    - jeremiastraub
    - herdeanu
