{% set name = "dantro" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f4c280c7ee8f09f0fd07a67bddd8245d68734e46ee5a9e3b48d0c864c99c85a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask >=2.10.1
    - distributed >=2.10.0
    - h5py >=3.1.0
    - matplotlib-base >=3.2.1
    - networkx >=2.2
    - numpy >=1.19.4
    - paramspace >=2.5.1
    - ruamel.yaml >=0.16.10
    - scipy >=1.5.3
    - sympy >=1.5.1
    - toolz >=0.10.0
    - xarray >=0.16.0
    - dill
    - seaborn

test:
  imports:
    - dantro
    - dantro.containers
    - dantro.data_loaders
    - dantro.groups
    - dantro.mixins
    - dantro.plot_creators
    - dantro.plot_creators.ext_funcs
    - dantro.proxy
    - dantro.utils
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://ts-gitlab.iup.uni-heidelberg.de/utopia/dantro
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Handle, transform, and visualize hierarchically structured data
  description: |
    dantro is a python package for handling, transforming, and visualizing
    hierarchically organized data.
    Integrated into data-intensive projects, it supplies an easy way to define
    a customizable, configuration-based data processing pipeline.
  doc_url: https://dantro.readthedocs.io
  dev_url: https://ts-gitlab.iup.uni-heidelberg.de/utopia/dantro

extra:
  recipe-maintainers:
    - blsqr
    - jeremiastraub
    - herdeanu
