{% set name = "dantro" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40d05141ec308c797a62ca71db60d8f3ffeaa8cd4bf760afb77b158735a269c8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask >=2.10.1
    - distributed >=2.10.0
    - h5py >=3.1
    - matplotlib-base >=3.2.1
    - networkx >=2.5
    - numpy >=1.17.4
    - paramspace >=2.5.1
    - ruamel.yaml >=0.16.10
    - scipy >=1.5.3
    - sympy >=1.6.1
    - toolz >=0.10.0
    - xarray >=0.16.0
    - seaborn >=0.11
    - dill >=0.3.3

test:
  imports:
    - dantro
    - dantro.containers
    - dantro.data_loaders
    - dantro.groups
    - dantro.mixins
    - dantro.plot_creators
    - dantro.plot_creators.ext_funcs
    - dantro.proxy
    - dantro.utils
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://ts-gitlab.iup.uni-heidelberg.de/utopia/dantro
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Handle, transform, and visualize hierarchically structured data
  description: |
    dantro is a python package for handling, transforming, and visualizing
    hierarchically organized data.
    Integrated into data-intensive projects, it supplies an easy way to define
    a customizable, configuration-based data processing pipeline.
  doc_url: https://dantro.readthedocs.io
  dev_url: https://ts-gitlab.iup.uni-heidelberg.de/utopia/dantro

extra:
  recipe-maintainers:
    - blsqr
    - jeremiastraub
    - herdeanu
